const ActionTypes = {
  BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
  AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
  LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
  LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
  CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS'
};

export default ActionTypes;
